version: '3'
services:
  django-weasyprint-app:
    build: .
    volumes:
      - ./generador/staticfiles:/app/generador/staticfiles
      - ./media:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    command: python manage.py runserver 0.0.0.0:8000
