version: '3'
services:
  django-weasyprint-app:
    build: .
    volumes:
      - .:/app
      - ./generador/staticfiles/css:/app/generador/staticfiles/css

    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    command: python manage.py runserver 0.0.0.0:8000
