# Generated by Django 4.2.15 on 2024-08-20 16:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_participante', models.CharField(max_length=100)),
                ('nombre_curso', models.CharField(max_length=200)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('token', models.CharField(blank=True, editable=False, max_length=64)),
                ('firma', models.BinaryField(blank=True)),
                ('codigo_qr', models.ImageField(blank=True, upload_to='codigos_qr/')),
            ],
        ),
    ]
